- name: Add Grafana APT key
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  apt_repository:
    repo: "deb https://apt.grafana.com stable main"
    state: present

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: true