- name: Set access for all servers
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Allow passwordless sudo for ansible_user
      copy:
        dest: "/etc/sudoers.d/{{ ansible_user }}"
        content: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL\n"
        owner: root
        group: root
        mode: '0440'

    - name: Gather facts manually after sudo fix
      setup:
