input {
  kafka {
    bootstrap_servers => "192.168.56.104:9092"
    topics => ["logs"]
	codec => "json"
  }
  
  beats {
    port => 5044
  }
}

filter {
	
	if [message] {
		mutate {
			lowercase => ["service"]
		}
	}
}

output {
	elasticsearch {
		hosts => ["http://192.168.56.103:9200"]
		index => "lgs-%{[service]}-%{+YYYY.MM.dd}"
	}
	
	stdout { codec => rubydebug }
}